[versions]
accompanistAppcompatTheme = "0.16.0"
activityCompose = "1.9.2"
android = "8.6.1"
androidx-core = "1.7.0"
androidx-appcompat = "1.6.1"
hiltAndroidCompiler = "2.42"
lifecycleRuntimeCompose = "2.8.7"
animation = "1.7.8"
composeBomVersion = "2025.03.00"
composeThemeAdapter = "1.2.1"
lifecycleRuntimeKtx = "2.5.2"
lifecycleViewmodelCompose = "2.8.7"
mapSdk = "3.21.0"
material = "1.8.0"
constraintlayout = "2.1.4"
naverMapCompose = "fc~cluster-SNAPSHOT"
naverMapLocation = "21.0.2"
naverMapClustering = "1.0.2"
navigationUi = "2.8.9"
playServicesLocation = "21.3.0"
navigationFragment = "2.9.3"
threetenabp = "1.4.4"
material-calendarview = "1.4.3"
recyclerview = "1.3.2"
transport-runtime = "3.1.2"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
activity = "1.8.2"
fragment = "1.6.2"
uiTestJunit4 = "1.7.8"
uiTooling = "1.7.8"
compose-material3 = "1.3.1"
workRuntimeKtx = "2.10.0"
datastore = "1.0.0"
composeBom = "2024.04.01"
lifecycle = "2.7.0"
retrofit = "2.9.0"
converter-gson = "2.9.0"
gson = "2.10.1"
okhttp = "4.12.0"
glide = "4.15.1"
glide-compiler = "4.12.0"
compressor = "3.0.1"
coroutines = "1.7.3"
kakao-login = "2.8.6"
hilt = "2.50"
androidxHilt = "1.2.0"
play-services-base = "18.0.1"
firebase-bom = "32.6.0"
firebase-crashlytics = "2.9.9"
google-services = "4.4.2"
timber = "5.0.1"
kotlin-android = "1.9.25"
ksp = "1.9.0-1.0.13"
ossLicenses = "17.3.0"
ossLicensesPlugin = "0.10.6"
glanceAppwidget = "1.1.1"
glanceAppwidgetPreview = "1.1.1"
glancePreview = "1.1.1"

[libraries]
# kotlinx, kotlin
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "navigationFragment" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui", version.ref = "navigationFragment" }

kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

# androidx
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
androidx-hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "androidxHilt" }
androidx-hilt-common = { group = "androidx.hilt", name = "hilt-common", version.ref = "androidxHilt" }
androidx-hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "androidxHilt" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }

# compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
androidx-compose-animation = { module = "androidx.compose.animation:animation", version.ref = "animation" }
androidx-compose-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeCompose" }
androidx-compose-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

# glance
androidx-glance-appwidget = { group = "androidx.glance", name = "glance-appwidget", version.ref = "glanceAppwidget" }
androidx-glance-appwidget-preview = { group = "androidx.glance", name = "glance-appwidget-preview", version.ref = "glanceAppwidgetPreview" }
androidx-glance-preview = { group = "androidx.glance", name = "glance-preview", version.ref = "glancePreview" }
androidx-glance-material3 = { group = "androidx.glance", name = "glance-material3", version.ref = "glanceAppwidget" }
androidx-glance = { group = "androidx.glance", name = "glance", version.ref = "glanceAppwidget" }

# glide
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide-compiler" }

# retrofit, okhttp, gson
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "converter-gson" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

# hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

# firebase
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-config = { group = "com.google.firebase", name = "firebase-config" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging" }
play-services-base = { group = "com.google.android.gms", name = "play-services-base", version.ref = "play-services-base" }

# etc
accompanist-appcompat-theme = { group = "com.google.accompanist", name = "accompanist-appcompat-theme", version.ref = "accompanistAppcompatTheme" }
compose-theme-adapter = { group = "com.google.android.material", name = "compose-theme-adapter", version.ref = "composeThemeAdapter" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
threetenabp = { group = "com.jakewharton.threetenabp", name = "threetenabp", version.ref = "threetenabp" }
material-calendarview = { group = "com.prolificinteractive", name = "material-calendarview", version.ref = "material-calendarview" }
transport-runtime = { group = "com.google.android.datatransport", name = "transport-runtime", version.ref = "transport-runtime" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
compressor = { group = "id.zelory", name = "compressor", version.ref = "compressor" }
kakao-login = { group = "com.kakao.sdk", name = "v2-user", version.ref = "kakao-login" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
oss-licenses = { group = "com.google.android.gms", name = "play-services-oss-licenses", version.ref = "ossLicenses" }
oss-licenses-plugin = { group = "com.google.android.gms", name = "oss-licenses-plugin", version.ref = "ossLicensesPlugin" }
map-sdk = { module = "com.naver.maps:map-sdk", version.ref = "mapSdk" }
naver-map-compose = { module = "com.github.ho8278:naver-map-compose", version.ref = "naverMapCompose" }
naver-map-location = { module = "io.github.fornewid:naver-map-location", version.ref = "naverMapLocation" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android" }
android-library = { id = "com.android.library", version.ref = "android" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-android" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
