name: Android CI

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    env:
      APP_KEY: ${{ secrets.APP_KEY }}
      BASE_URL: ${{ secrets.BASE_URL }}
      KAKAO_NATIVE_APP_KEY: ${{ secrets.KAKAO_NATIVE_APP_KEY }}
      KAKAO_REDIRECTION_SCHEME: ${{ secrets.KAKAO_REDIRECTION_SCHEME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17 # Change this to your desired Java version
          distribution: 'jdk' # Replace with your desired distribution ("adopt", "zulu", "temurin", or "jdk")
          architecture: x64

      - name: Build and test
        run: ./gradlew build # Adjust this command according to your project's build process

