name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: BASE_URL
      run: |
        echo BASE_URL=\"$BASE_URL\" >> local.properties
      shell: bash
      env:
       BASE_URL: ${{ secrets.BASE_URL}}

    - name: KAKAO_NATIVE_APP_KEY
      run: |
        echo KAKAO_NATIVE_APP_KEY=$KAKAO_NATIVE_APP_KEY >> local.properties
      shell: bash
      env:
        APP_KEY: ${{ secrets.KAKAO_NATIVE_APP_KEY }}

  
    - name: Generate google-services.json
      run: |
        echo "$GOOGLE_SERVICE" > app/google-services.json.b64
        base64 -d -i app/google-services.json.b64 > app/google-services.json
      env:
        GOOGLE_SERVICE: ${{ secrets.GOOGLE_SERVICE }}
    
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
