name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: base_url
      run: |
        echo base_url=\"$base_url\" > local.properties
      shell: bash
      env:
       BASE_URL: ${{ secrets.BASE_URL}}
   
    - name: app_key
      run: |
        echo app_key=\"$app_key\" > local.properties
      shell: bash
      env:
        APP_KEY: ${{ secrets.APP_KEY }}
        
    - name: kakao_app_key
      run: |
        echo kakao_app_key=\"$kakao_app_key\" > local.properties
      shell: bash
      env:
        APOD_API_KEY: ${{ secrets.kakao_app_key }}

    - name: kakao_native_app_key
      run: |
        echo kakao_native_app_key=\"$kakao_native_app_key\" > local.properties
      shell: bash
      env:
        APOD_API_KEY: ${{ secrets.kakao_native_app_key }}

