name: Android CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Create Local Properties
      run: touch local.properties

    - name: Access Local Properties
      env:
        DEV_BASE_URL: ${{ secrets.DEV_BASE_URL }}
        PROD_BASE_URL: ${{ secrets.PROD_BASE_URL }}
        KAKAO_APP_KEY: ${{ secrets.KAKAO_NATIVE_APP_KEY }}
      run: |
        echo DEV_BASE_URL=\"$DEV_BASE_URL\" >> local.properties
        echo PROD_BASE_URL=\"$PROD_BASE_URL\" >> local.properties
        echo KAKAO_NATIVE_APP_KEY=$KAKAO_NATIVE_APP_KEY >> local.properties
  
    - name: Generate google-services.json
      run: |
        echo "$GOOGLE_SERVICE" > app/google-services.json.b64
        base64 -d -i app/google-services.json.b64 > app/google-services.json
      env:
        GOOGLE_SERVICE: ${{ secrets.GOOGLE_SERVICE }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
