name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:  # Define your environment variables here
      BASE_URL: ${{ secrets.BASE_URL }}
      APP_KEY: ${{ secrets.APP_KEY }}
      KAKAO_NATIVE_APP_KEY: ${{ secrets.KAKAO_NATIVE_APP_KEY }}
      KAKAO_REDIRECTION_SCHEME: ${{ secrets.KAKAO_REDIRECTION_SCHEME }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build and Test
        run: |
          # You can use the environment variables in your build commands
          ./gradlew assembleDebug -PbaseUrl=$BASE_URL -PappKey=$APP_KEY
