name: Android APK Build and Slack Upload

on:
  workflow_dispatch:  # 버튼을 누를 시 실행되도록 설정
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'qa'
        type: choice
        options:
          - qa
          - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Create Local Properties
      run: touch local.properties

    - name: Access Local Properties
      env:
        DEV_BASE_URL: ${{ secrets.DEV_BASE_URL }}
        PROD_BASE_URL: ${{ secrets.PROD_BASE_URL }}
        KAKAO_APP_KEY: ${{ secrets.KAKAO_NATIVE_APP_KEY }}
      run: |
        echo DEV_BASE_URL=\"$DEV_BASE_URL\" >> local.properties
        echo PROD_BASE_URL=\"$PROD_BASE_URL\" >> local.properties
        echo KAKAO_NATIVE_APP_KEY=$KAKAO_APP_KEY >> local.properties

    - name: Generate google-services.json
      run: |
        echo "$GOOGLE_SERVICE" > app/google-services.json.b64
        base64 -d -i app/google-services.json.b64 > app/google-services.json
      env:
        GOOGLE_SERVICE: ${{ secrets.GOOGLE_SERVICE }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Slack - Send Msg
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: workflow,commit,repo,author,job,ref,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Slack - Upload APK
      if: github.event_name == 'workflow_dispatch'
      uses: MeilCli/slack-upload-file@v4
      with:
        slack_token: ${{ secrets.SLACK_TOKEN }}
        channel_id: ${{ secrets.SLACK_CHANNEL }}
        initial_comment: 'APK 빌드가 완료되었습니다.'
        file_type: 'apk'
        file_name: 'app-debug.apk'
        file_path: './app/build/outputs/apk/debug/app-debug.apk'
