name: Release Tag

on: 
  pull_request:
    branches:
      - production
    types:
      - closed
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: 브랜치명에서 버전 정보 추출
      id: extract_version_name
      run: |
        # 브랜치 이름에서 버전 번호 추출
        echo "Branch Name: ${{ github.event.pull_request.head.ref }}"
        VERSION=$(echo "${{ github.event.pull_request.head.ref }}" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
        echo "Extracted Version: $VERSION"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
      
    - name: Release 생성 
      uses: actions/create-release@v1
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
        tag_name: ${{ steps.extract_version_name.outputs.version }} 
        release_name: ${{ steps.extract_version_name.outputs.version }}
